config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  before_action :set_flat, only: %i[show edit update destroy]

  def index
    @flats = Flat.all
  end

  def show

  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def edit

  end

  def update

  end

  def destroy

  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(%i[name address description price_per_night number_of_guests])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <div class="row mt-3">
    <h1>All our Flats (<%= @flats.length %>)</h1>
  </div>

  <div class="row gy-3">

    <% @flats.each do |flat| %>
    <div class="col-4 ">
      <div class="col-12 border p-0 rounded card">
        <div class="px-2 pt-2 bg-light border-bottom">
          <h3><%= flat.name %></h3>
          <p><%= flat.address %></p>
          <p class='pb-2'><i class="fas fa-user-friends"></i> <%= flat.number_of_guests %>      <i class="fas fa-dollar-sign"></i> <%= flat.price_per_night %></p>
        </div>
        <div class="px-3 py-2">
          <%= link_to 'More info', flat_path(flat) %>
        </div>
      </div>
    </div>
    <% end %>



  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-3">
      <h2>Create your flat</h2>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-6">
      <div class="row">
        <%= simple_form_for @flat do |f| %>
        <div class="col-12 mt-2">
          <%= f.input :name, label: false, placeholder: %{Your flat's name here!} %>
        </div>
        <div class="col-12 mt-2">
          <%= f.input :address, label: false, placeholder: %{Your flat's address here!} %>
        </div>
        <div class="col-12 mt-2">
          <%= f.input :description, label: false, placeholder: %{Give us a brief description of your place}, as: :text %>
        </div>
        <div class="row mt-2">
          <div class="col-6">
            <%= f.input :price_per_night, label: false, placeholder: %{Price per night} %>
          </div>
          <div class="col-6">
          <%= f.input :number_of_guests, label: false, placeholder: %{Max number of guests} %>
          </div>
        </div>

        <div class="col-12 d-flex justify-content-center">
          <%= f.submit class:'btn btn-primary mt-2'%>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="banner container-fluid"></div>

<div class="container">
  <div class="row show-contaier">
    <div class="col-8">
      <div class="row justify-content-around">
        <div class="col-10 bg-light rounded first-lvl a-shadow">
          <h2 class='pt-2'><%= @flat.name %></h2>
          <p><%= @flat.address %></p>
        </div>
        <div class="col-10 mt-3 bg-light rounded a-shadow">
          <h3>Alittle more about this flat...</h3>
          <p><%= @flat.description %></p>
        </div>
      </div>


    </div>

    <div class="col-4">
      <div class="row justify-content-start">
        <div class="col-8 bg-light rounded pt-2">
          <div class="row">
            <div class="col-12">
              <h2>Book this place</h2>
              <form action="#">
                <div class='border'>
                  <label for="start-date" class='col-3 ps-3 py-1 border-end'>From:</label>
                  <input type="date" class="col-8">
                </div>
                <div class="border">
                <label for="end-date" class="col-3 ps-3 py-1 border-end">To:</label>
                <input type="date" class='col-8'>
                </div>
                <div class="col-12 d-flex justify-content-center p-2">
                <input type="submit" class='btn btn-primary'>
                </div>

              </form>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/8af68b1bcc.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="container-fluid bg-light">
      <div class="row py-2 justify-content-between">
      <div class="col-3 d-flex align-items-center">
        <h4 class='m-0'>Simple Airbnb</h4>
      </div>
      <div class="col-3 d-flex align-items-center justify-content-end">
        <%= link_to 'Add Flat', new_flat_path, class:'btn btn-white border-primary text-primary' %>
      </div>
      </div>
    </header>
      <%= yield %>
  </body>
</html>